#############################################################################
# Makefile for building: digilent-agent.app/Contents/MacOS/digilent-agent
# Generated by qmake (3.1) (Qt 5.9.0)
# Project:  digilent-agent.pro
# Template: app
# Command: /usr/local/bin/qmake -o digilent-agent.xcodeproj/project.pbxproj digilent-agent.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /usr/local/Cellar/qt/5.9.0_1/bin/moc
UIC       = /usr/local/Cellar/qt/5.9.0_1/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
INCPATH       = -I. -Isrc/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.9.0_1/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_mainWindow.cpp moc_predefs.h moc_httplistener.cpp moc_httpconnectionhandler.cpp moc_httpconnectionhandlerpool.cpp\
	 moc_httprequesthandler.cpp moc_httpsessionstore.cpp moc_staticfilecontroller.cpp\
	 moc_httpRouter.cpp moc_mainWindow.cpp moc_comboBoxEventFilter.cpp\
	 moc_agentConfigCtrl.cpp moc_debugController.cpp moc_agent.cpp\
	 moc_wflDevice.cpp moc_serial.cpp moc_wflSerialDevice.cpp\
	 moc_httpClient.cpp ui_mainWindow.h
compiler_rcc_make_all: qrc_mainWindow.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_mainWindow.cpp
qrc_mainWindow.cpp: mainWindow.qrc \
		/usr/local/Cellar/qt/5.9.0_1/bin/rcc \
		images/icon.png \
		images/refresh-arrow.png
	/usr/local/Cellar/qt/5.9.0_1/bin/rcc -name mainWindow mainWindow.qrc -o qrc_mainWindow.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.9.0_1/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.9.0_1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_httplistener.cpp moc_httpconnectionhandler.cpp moc_httpconnectionhandlerpool.cpp moc_httprequesthandler.cpp moc_httpsessionstore.cpp moc_staticfilecontroller.cpp moc_httpRouter.cpp moc_mainWindow.cpp moc_comboBoxEventFilter.cpp moc_agentConfigCtrl.cpp moc_debugController.cpp moc_agent.cpp moc_wflDevice.cpp moc_serial.cpp moc_wflSerialDevice.cpp moc_httpClient.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_httplistener.cpp moc_httpconnectionhandler.cpp moc_httpconnectionhandlerpool.cpp moc_httprequesthandler.cpp moc_httpsessionstore.cpp moc_staticfilecontroller.cpp moc_httpRouter.cpp moc_mainWindow.cpp moc_comboBoxEventFilter.cpp moc_agentConfigCtrl.cpp moc_debugController.cpp moc_agent.cpp moc_wflDevice.cpp moc_serial.cpp moc_wflSerialDevice.cpp moc_httpClient.cpp
moc_httplistener.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QTcpServer \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QBasicTimer \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbasictimer.h \
		src/httpServer/core/httpglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QtGlobal \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qglobal.h \
		src/httpServer/core/httpconnectionhandler.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QSslConfiguration \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslconfiguration.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthread.h \
		src/httpServer/core/httprequest.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMultiMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTemporaryFile \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QUuid \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/quuid.h \
		src/httpServer/core/httprequesthandler.h \
		src/httpServer/core/httpresponse.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		src/httpServer/core/httpcookie.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		src/httpServer/core/httpconnectionhandlerpool.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMutex \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmutex.h \
		src/httpServer/core/httplistener.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/httpServer/core/httplistener.h -o moc_httplistener.cpp

moc_httpconnectionhandler.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QSslConfiguration \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslconfiguration.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthread.h \
		src/httpServer/core/httpglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QtGlobal \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qglobal.h \
		src/httpServer/core/httprequest.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMultiMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTemporaryFile \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QUuid \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/quuid.h \
		src/httpServer/core/httprequesthandler.h \
		src/httpServer/core/httpresponse.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		src/httpServer/core/httpcookie.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		src/httpServer/core/httpconnectionhandler.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/httpServer/core/httpconnectionhandler.h -o moc_httpconnectionhandler.cpp

moc_httpconnectionhandlerpool.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMutex \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmutex.h \
		src/httpServer/core/httpglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QtGlobal \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qglobal.h \
		src/httpServer/core/httpconnectionhandler.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QSslConfiguration \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslconfiguration.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthread.h \
		src/httpServer/core/httprequest.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMultiMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTemporaryFile \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QUuid \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/quuid.h \
		src/httpServer/core/httprequesthandler.h \
		src/httpServer/core/httpresponse.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		src/httpServer/core/httpcookie.h \
		src/httpServer/core/httpconnectionhandlerpool.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/httpServer/core/httpconnectionhandlerpool.h -o moc_httpconnectionhandlerpool.cpp

moc_httprequesthandler.cpp: src/httpServer/core/httpglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QtGlobal \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qglobal.h \
		src/httpServer/core/httprequest.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMultiMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTemporaryFile \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QUuid \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/quuid.h \
		src/httpServer/core/httpresponse.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		src/httpServer/core/httpcookie.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		src/httpServer/core/httprequesthandler.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/httpServer/core/httprequesthandler.h -o moc_httprequesthandler.cpp

moc_httpsessionstore.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTimer \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMutex \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmutex.h \
		src/httpServer/core/httpglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QtGlobal \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qglobal.h \
		src/httpServer/core/httpsession.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QVariant \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QReadWriteLock \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qreadwritelock.h \
		src/httpServer/core/httpresponse.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		src/httpServer/core/httpcookie.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		src/httpServer/core/httprequest.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMultiMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTemporaryFile \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QUuid \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/quuid.h \
		src/httpServer/core/httpsessionstore.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/httpServer/core/httpsessionstore.h -o moc_httpsessionstore.cpp

moc_staticfilecontroller.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QCache \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcache.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMutex \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmutex.h \
		src/httpServer/core/httpglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QtGlobal \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qglobal.h \
		src/httpServer/core/httprequest.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMultiMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTemporaryFile \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QUuid \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/quuid.h \
		src/httpServer/core/httpresponse.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		src/httpServer/core/httpcookie.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		src/httpServer/core/httprequesthandler.h \
		src/httpServer/core/staticfilecontroller.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/httpServer/core/staticfilecontroller.h -o moc_staticfilecontroller.cpp

moc_httpRouter.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QtCore \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qabstractanimation.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qabstracteventdispatcher.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qabstractnativeeventfilter.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qabstractproxymodel.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qabstractstate.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qabstracttransition.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qalgorithms.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qanimationgroup.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qarraydata.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qarraydataops.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qarraydatapointer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qatomic.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbasictimer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbitarray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbuffer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearraylist.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearraymatcher.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcache.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qchar.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcollator.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcommandlineoption.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcommandlineparser.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcompilerdetection.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcontainerfwd.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcontiguouscache.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcoreapplication.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcoreevent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcryptographichash.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdatastream.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdatetime.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdeadlinetimer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdir.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdiriterator.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qeasingcurve.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qelapsedtimer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qendian.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qeventloop.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qeventtransition.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qexception.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfactoryinterface.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfiledevice.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfileinfo.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfileselector.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfilesystemwatcher.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfinalstate.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qflags.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfuture.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfutureinterface.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfuturesynchronizer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qfuturewatcher.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qgenericatomic.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qglobalstatic.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qhash.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qhashfunctions.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qhistorystate.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qidentityproxymodel.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qiodevice.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qisenum.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qitemselectionmodel.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qiterator.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qjsonarray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qjsondocument.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qjsonobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qjsonvalue.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qlibrary.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qlibraryinfo.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qline.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qlinkedlist.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qlist.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qlocale.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qlockfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qloggingcategory.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmargins.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmath.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmessageauthenticationcode.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmetaobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmetatype.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmimedata.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmimedatabase.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmimetype.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmutex.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qnamespace.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qnumeric.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobjectcleanuphandler.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobjectdefs.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qoperatingsystemversion.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qpair.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qparallelanimationgroup.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qpauseanimation.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qplugin.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qpluginloader.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qpoint.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qpointer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qprocess.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qprocessordetection.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qpropertyanimation.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qqueue.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qreadwritelock.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qrect.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qrefcount.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qregexp.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qregularexpression.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qresource.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qresultstore.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qrunnable.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsavefile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qscopedpointer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qscopedvaluerollback.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsemaphore.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsequentialanimationgroup.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qset.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qshareddata.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsharedmemory.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsharedpointer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsignalmapper.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsignaltransition.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsize.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsocketnotifier.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsortfilterproxymodel.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstack.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstandardpaths.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstate.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstatemachine.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstorageinfo.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstringbuilder.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstringlist.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstringlistmodel.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstringmatcher.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsysinfo.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsystemdetection.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsystemsemaphore.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtemporarydir.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtextboundaryfinder.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtextcodec.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtextstream.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthread.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthreadpool.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthreadstorage.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtimeline.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtimer.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtimezone.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtranslator.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtypeinfo.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtypetraits.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qurl.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qurlquery.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/quuid.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qvariant.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qvariantanimation.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qvarlengtharray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qversionnumber.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qversiontagging.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qwaitcondition.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qwineventnotifier.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qxmlstream.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtcoreversion.h \
		src/core/agent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		lib/digilent/qtSerial/serial.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPort \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialport.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPortInfo \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		lib/digilent/pgm/digilentPgm.h \
		lib/digilent/pgm/pgmBlock.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		src/wflDevice/wflDevice.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QThread \
		src/wflDevice/wflSerialDevice.h \
		src/httpServer/core/httprequesthandler.h \
		src/httpServer/core/httpglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QtGlobal \
		src/httpServer/core/httprequest.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMultiMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTemporaryFile \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QUuid \
		src/httpServer/core/httpresponse.h \
		src/httpServer/core/httpcookie.h \
		src/httpServer/core/staticfilecontroller.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QCache \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMutex \
		src/httpServer/agentConfigCtrl.h \
		src/httpServer/httpRouter.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/httpServer/httpRouter.h -o moc_httpRouter.cpp

moc_mainWindow.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QtNetwork \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtnetworkglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qabstractnetworkcache.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qabstractsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qauthenticator.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qdnslookup.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostinfo.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhstspolicy.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhttpmultipart.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qlocalserver.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qlocalsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkconfigmanager.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkconfiguration.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkcookie.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkcookiejar.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkdatagram.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkdiskcache.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkinterface.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkproxy.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkreply.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkrequest.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworksession.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsctpserver.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsctpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qssl.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslcertificate.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslcertificateextension.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslcipher.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslconfiguration.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qssldiffiehellmanparameters.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslellipticcurve.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslerror.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslkey.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslpresharedkeyauthenticator.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qsslsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpserver.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qudpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtnetworkversion.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/QSystemTrayIcon \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/qsystemtrayicon.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/QPushButton \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/QLineEdit \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/qlineedit.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/QComboBox \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/qcombobox.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QEvent \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qcoreevent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/QLabel \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/qlabel.h \
		src/core/agent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qjsonobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		lib/digilent/qtSerial/serial.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPort \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialport.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPortInfo \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		lib/digilent/pgm/digilentPgm.h \
		lib/digilent/pgm/pgmBlock.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		src/wflDevice/wflDevice.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthread.h \
		src/wflDevice/wflSerialDevice.h \
		src/core/comboBoxEventFilter.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/QMainWindow \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers/qmainwindow.h \
		src/mainWindow.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/mainWindow.h -o moc_mainWindow.cpp

moc_comboBoxEventFilter.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		src/core/comboBoxEventFilter.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/core/comboBoxEventFilter.h -o moc_comboBoxEventFilter.cpp

moc_agentConfigCtrl.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qjsonobject.h \
		src/httpServer/core/httprequesthandler.h \
		src/httpServer/core/httpglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QtGlobal \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qglobal.h \
		src/httpServer/core/httprequest.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMultiMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTemporaryFile \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QUuid \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/quuid.h \
		src/httpServer/core/httpresponse.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		src/httpServer/core/httpcookie.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		src/core/agent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		lib/digilent/qtSerial/serial.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPort \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialport.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPortInfo \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		lib/digilent/pgm/digilentPgm.h \
		lib/digilent/pgm/pgmBlock.h \
		src/wflDevice/wflDevice.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthread.h \
		src/wflDevice/wflSerialDevice.h \
		src/httpServer/agentConfigCtrl.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/httpServer/agentConfigCtrl.h -o moc_agentConfigCtrl.cpp

moc_debugController.cpp: src/httpServer/core/httprequesthandler.h \
		src/httpServer/core/httpglobal.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QtGlobal \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qglobal.h \
		src/httpServer/core/httprequest.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QHostAddress \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qhostaddress.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QTcpSocket \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qtcpsocket.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qmap.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QMultiMap \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QSettings \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qsettings.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QTemporaryFile \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qtemporaryfile.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QUuid \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/quuid.h \
		src/httpServer/core/httpresponse.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		src/httpServer/core/httpcookie.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		src/httpServer/debugController.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/httpServer/debugController.h -o moc_debugController.cpp

moc_agent.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QJsonObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qjsonobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QVector \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qvector.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		lib/digilent/qtSerial/serial.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPort \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialport.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPortInfo \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		lib/digilent/pgm/digilentPgm.h \
		lib/digilent/pgm/pgmBlock.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QByteArray \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qbytearray.h \
		src/wflDevice/wflDevice.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthread.h \
		src/wflDevice/wflSerialDevice.h \
		src/core/agent.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/core/agent.h -o moc_agent.cpp

moc_wflDevice.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthread.h \
		src/wflDevice/wflDevice.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/wflDevice/wflDevice.h -o moc_wflDevice.cpp

moc_serial.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPort \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialport.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPortInfo \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		lib/digilent/qtSerial/serial.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib lib/digilent/qtSerial/serial.h -o moc_serial.cpp

moc_wflSerialDevice.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QThread \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qthread.h \
		src/wflDevice/wflDevice.h \
		lib/digilent/qtSerial/serial.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QDebug \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qdebug.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/QList \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers/qevent.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPort \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialport.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/QSerialPortInfo \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers/qserialportinfo.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QString \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qstring.h \
		src/wflDevice/wflSerialDevice.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib src/wflDevice/wflSerialDevice.h -o moc_wflSerialDevice.cpp

moc_httpClient.cpp: /usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/QObject \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers/qobject.h \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/QNetworkAccessManager \
		/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers/qnetworkaccessmanager.h \
		lib/digilent/qtHttp/httpClient.h \
		moc_predefs.h \
		/usr/local/Cellar/qt/5.9.0_1/bin/moc
	/usr/local/Cellar/qt/5.9.0_1/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -I/Users/digilent/git/digilent/digilent-agent -I/Users/digilent/git/digilent/digilent-agent/src/httpServer/core -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include -IC:/Qt/Tools/mingw530_32/lib/gcc/i686-w64-mingw32/5.3.0/include-fixed -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++ -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw530_32/i686-w64-mingw32/include/c++/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/usr/local/Cellar/qt/5.9.0_1/lib lib/digilent/qtHttp/httpClient.h -o moc_httpClient.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainWindow.h
ui_mainWindow.h: mainWindow.ui \
		/usr/local/Cellar/qt/5.9.0_1/bin/uic
	/usr/local/Cellar/qt/5.9.0_1/bin/uic mainWindow.ui -o ui_mainWindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

