#############################################################################
# Makefile for building: digilent-agent.app/Contents/MacOS/digilent-agent
# Generated by qmake (3.1) (Qt 5.9.0)
# Project:  digilent-agent.pro
# Template: app
# Command: /usr/local/bin/qmake -o project.pbxproj digilent-agent.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

MOC       = /usr/local/Cellar/qt/5.9.0_1/bin/moc
UIC       = /usr/local/Cellar/qt/5.9.0_1/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SERIALPORT_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
INCPATH       = -I. -I/usr/local/Cellar/qt/5.9.0_1/lib/QtWidgets.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtGui.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtNetwork.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtSerialPort.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtConcurrent.framework/Headers -I/usr/local/Cellar/qt/5.9.0_1/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/Cellar/qt/5.9.0_1/mkspecs/macx-clang -F/usr/local/Cellar/qt/5.9.0_1/lib
DEL_FILE  = rm -f
MOVE      = mv -f

preprocess: compilers
clean preprocess_clean: compiler_clean

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compilers: qrc_mainWindow.cpp moc_predefs.h ui_mainWindow.h
compiler_rcc_make_all: qrc_mainWindow.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_mainWindow.cpp
qrc_mainWindow.cpp: mainWindow.qrc \
		/usr/local/Cellar/qt/5.9.0_1/bin/rcc \
		images/icon.png \
		images/refresh-arrow.png
	/usr/local/Cellar/qt/5.9.0_1/bin/rcc -name mainWindow mainWindow.qrc -o qrc_mainWindow.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/local/Cellar/qt/5.9.0_1/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++11 -dM -E -o moc_predefs.h /usr/local/Cellar/qt/5.9.0_1/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainWindow.h
ui_mainWindow.h: mainWindow.ui \
		/usr/local/Cellar/qt/5.9.0_1/bin/uic
	/usr/local/Cellar/qt/5.9.0_1/bin/uic mainWindow.ui -o ui_mainWindow.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_uic_clean 

